export interface Unit {
  id: string;
  title: string;
  order: number;
  description: string;
}

export interface TopicMeta {
  slug: string;
  title: string;
  hook: string;
  unitId: string;
  order: number;
  difficulty: number; // 1 to 3
  thumbnail: 'histogram' | 'curve' | 'matrix' | 'levels' | 'cdf';
  prerequisites: string[];
}

export const UNITS: Unit[] = [
  {
    id: 'digital-image-fundamentals',
    title: 'Unit 1: Digital Image Fundamentals',
    order: 1,
    description:
      'Explore continuous 2D light scenes, sampling resolution, intensity quantization, matrix storage, and probability foundations.',
  },
  {
    id: 'histogram-processing',
    title: 'Unit 2: Histogram Processing',
    order: 2,
    description:
      'Master intensity distributions, contrast enhancement, histogram equalization, target matching, CDF mapping, and local CLAHE.',
  },
  {
    id: 'spatial-filtering',
    title: 'Unit 3: Spatial Filtering',
    order: 3,
    description:
      'Move from single pixels to neighbourhoods: kernels, convolution, box and Gaussian smoothing, and the price paid at edges.',
  },
  {
    id: 'bilateral-filtering',
    title: 'Unit 4: Bilateral Filtering',
    order: 4,
    description:
      'Fix the edge-blurring problem from Unit 3 by adding a second, intensity-aware weight — smooth flat regions, leave real edges alone.',
  },
  {
    id: 'image-formation-enhancement',
    title: 'Unit 5: Image Formation & Enhancement',
    order: 5,
    description:
      'Decompose an image into illumination × reflectance (Retinex), then correct brightness perceptually with gamma / power-law curves.',
  },
];

export const TOPICS: TopicMeta[] = [
  // --- Unit 1 ---
  {
    slug: 'digital-image',
    title: 'Digital Image',
    hook: 'How continuous physical light is captured through 2D spatial sampling and intensity quantization.',
    unitId: 'digital-image-fundamentals',
    order: 1,
    difficulty: 1,
    thumbnail: 'matrix',
    prerequisites: [],
  },
  {
    slug: 'grayscale-image',
    title: 'Grayscale Image',
    hook: 'Transforming 3-channel RGB color spectra into scalar luminance using standard perceptual human eye weights.',
    unitId: 'digital-image-fundamentals',
    order: 2,
    difficulty: 1,
    thumbnail: 'levels',
    prerequisites: ['digital-image'],
  },
  {
    slug: 'pixel-intensity',
    title: 'Pixel Intensity',
    hook: 'Probing localized brightness values and extracting spatial line profiles across an image.',
    unitId: 'digital-image-fundamentals',
    order: 3,
    difficulty: 1,
    thumbnail: 'curve',
    prerequisites: ['grayscale-image'],
  },
  {
    slug: 'intensity-levels',
    title: '8-bit Image / Intensity Levels',
    hook: 'Visualizing false contouring and posterization when reducing bit-depth from 8-bit down to 1-bit.',
    unitId: 'digital-image-fundamentals',
    order: 4,
    difficulty: 1,
    thumbnail: 'levels',
    prerequisites: ['pixel-intensity'],
  },
  {
    slug: 'image-as-matrix',
    title: 'Image Representation as a Matrix',
    hook: 'Inspecting an M×N matrix of numeric intensity values with real-time cell editing and heatmaps.',
    unitId: 'digital-image-fundamentals',
    order: 5,
    difficulty: 1,
    thumbnail: 'matrix',
    prerequisites: ['intensity-levels'],
  },
  {
    slug: 'intensity-transformation',
    title: 'Intensity Transformation',
    hook: 'Point processing functions s = T(r): gamma correction, log compression, and live calculus derivatives.',
    unitId: 'digital-image-fundamentals',
    order: 6,
    difficulty: 2,
    thumbnail: 'curve',
    prerequisites: ['image-as-matrix'],
  },
  {
    slug: 'image-histogram',
    title: 'Image Histogram',
    hook: 'Frequency counts h(r_k) = n_k, statistical moments, entropy, and interactive range pixel masking.',
    unitId: 'digital-image-fundamentals',
    order: 7,
    difficulty: 1,
    thumbnail: 'histogram',
    prerequisites: ['intensity-transformation'],
  },
  {
    slug: 'intensity-probability',
    title: 'Probability Distribution of Intensities',
    hook: 'Treating intensity as a random variable and watching Monte Carlo pixel sampling converge to true p(r_k).',
    unitId: 'digital-image-fundamentals',
    order: 8,
    difficulty: 2,
    thumbnail: 'histogram',
    prerequisites: ['image-histogram'],
  },
  {
    slug: 'pdf',
    title: 'Probability Density Function (PDF)',
    hook: 'Transitioning from discrete histogram bins to a continuous density p_r(r) with shaded area integration.',
    unitId: 'digital-image-fundamentals',
    order: 9,
    difficulty: 2,
    thumbnail: 'cdf',
    prerequisites: ['intensity-probability'],
  },
  {
    slug: 'cdf',
    title: 'Cumulative Distribution Function (CDF)',
    hook: 'Running total c(r) = P(R ≤ r), monotonicity, and demonstrating the derivative relation dc/dr = p(r).',
    unitId: 'digital-image-fundamentals',
    order: 10,
    difficulty: 2,
    thumbnail: 'cdf',
    prerequisites: ['pdf'],
  },

  // --- Unit 2 ---
  {
    slug: 'histogram-equalization',
    title: 'Histogram Equalization',
    hook: 'Maximizing image contrast by flattening intensity distributions using scaled cumulative probabilities.',
    unitId: 'histogram-processing',
    order: 11,
    difficulty: 2,
    thumbnail: 'histogram',
    prerequisites: ['cdf'],
  },
  {
    slug: 'equalization-mapping',
    title: 'Equalization Mapping Function',
    hook: 'Proof that output density p_s(s) is strictly uniform using the Fundamental Theorem of Calculus.',
    unitId: 'histogram-processing',
    order: 12,
    difficulty: 3,
    thumbnail: 'curve',
    prerequisites: ['histogram-equalization'],
  },
  {
    slug: 'normalized-histogram',
    title: 'Normalized Histogram',
    hook: 'Scaling counts by total pixels M·N to ensure invariance to image resolution and compute distances.',
    unitId: 'histogram-processing',
    order: 13,
    difficulty: 1,
    thumbnail: 'histogram',
    prerequisites: ['histogram-equalization'],
  },
  {
    slug: 'histogram-transformation',
    title: 'Histogram Transformation',
    hook: 'How transformation curves reshape histograms via p_s(s) = p_r(r)|dr/ds| and bin-merging dynamics.',
    unitId: 'histogram-processing',
    order: 14,
    difficulty: 2,
    thumbnail: 'curve',
    prerequisites: ['equalization-mapping'],
  },
  {
    slug: 'inverse-histogram-transformation',
    title: 'Inverse Transformation',
    hook: 'Reversing transformations r = T⁻¹(s), monotonicity constraints, and round-trip error visualization.',
    unitId: 'histogram-processing',
    order: 15,
    difficulty: 2,
    thumbnail: 'curve',
    prerequisites: ['histogram-transformation'],
  },
  {
    slug: 'histogram-matching',
    title: 'Histogram Matching',
    hook: 'Transforming an image so its histogram matches another target image using double equalization.',
    unitId: 'histogram-processing',
    order: 16,
    difficulty: 3,
    thumbnail: 'histogram',
    prerequisites: ['inverse-histogram-transformation'],
  },
  {
    slug: 'histogram-specification',
    title: 'Histogram Specification',
    hook: 'Designing customized multi-modal Gaussian target shapes and computing discrete quantization residuals.',
    unitId: 'histogram-processing',
    order: 17,
    difficulty: 3,
    thumbnail: 'histogram',
    prerequisites: ['histogram-matching'],
  },
  {
    slug: 'cdf-matching',
    title: 'CDF Matching',
    hook: 'Interactive staircase walk aligning source CDF to target CDF to determine exact intensity remappings.',
    unitId: 'histogram-processing',
    order: 18,
    difficulty: 2,
    thumbnail: 'cdf',
    prerequisites: ['histogram-specification'],
  },
  {
    slug: 'global-histogram-processing',
    title: 'Global Histogram Processing',
    hook: 'Understanding why a single global LUT fails on scenes with mixed shadow and highlight regions.',
    unitId: 'histogram-processing',
    order: 19,
    difficulty: 2,
    thumbnail: 'histogram',
    prerequisites: ['cdf-matching'],
  },
  {
    slug: 'local-vs-global',
    title: 'Local vs. Global (CLAHE)',
    hook: 'Adaptive histogram equalization with tile grid division, clip limit redistribution, and bilinear blending.',
    unitId: 'histogram-processing',
    order: 20,
    difficulty: 3,
    thumbnail: 'matrix',
    prerequisites: ['global-histogram-processing'],
  },
  {
    slug: 'spatial-filtering',
    title: 'Spatial Filtering',
    hook: 'Output pixels computed from a pixel and its neighbours, not the pixel alone.',
    unitId: 'spatial-filtering',
    order: 21,
    difficulty: 1,
    thumbnail: 'matrix',
    prerequisites: ['local-vs-global'],
  },
  {
    slug: 'neighborhood-processing',
    title: 'Neighborhood Processing',
    hook: 'Slide a window over the image and let context decide each result.',
    unitId: 'spatial-filtering',
    order: 22,
    difficulty: 1,
    thumbnail: 'matrix',
    prerequisites: ['spatial-filtering'],
  },
  {
    slug: 'kernel-mask',
    title: 'Kernel / Mask',
    hook: 'A tiny matrix of weights that defines what a filter does.',
    unitId: 'spatial-filtering',
    order: 23,
    difficulty: 1,
    thumbnail: 'matrix',
    prerequisites: ['neighborhood-processing'],
  },
  {
    slug: 'convolution-filtering',
    title: 'Convolution / Filtering',
    hook: 'Multiply, add, slide: watch a kernel produce one output pixel.',
    unitId: 'spatial-filtering',
    order: 24,
    difficulty: 2,
    thumbnail: 'matrix',
    prerequisites: ['kernel-mask'],
  },
  {
    slug: 'box-filter',
    title: 'Box Filter',
    hook: 'Every neighbour gets the same weight. The simplest blur.',
    unitId: 'spatial-filtering',
    order: 25,
    difficulty: 1,
    thumbnail: 'levels',
    prerequisites: ['convolution-filtering'],
  },
  {
    slug: 'mean-filter',
    title: 'Mean / Averaging Filter',
    hook: 'Replace each pixel by its neighbourhood average to cancel noise.',
    unitId: 'spatial-filtering',
    order: 26,
    difficulty: 1,
    thumbnail: 'levels',
    prerequisites: ['box-filter'],
  },
  {
    slug: 'smoothing',
    title: 'Smoothing',
    hook: 'Low-pass filtering: keep slow changes, suppress rapid ones.',
    unitId: 'spatial-filtering',
    order: 27,
    difficulty: 2,
    thumbnail: 'curve',
    prerequisites: ['mean-filter'],
  },
  {
    slug: 'gaussian-filtering',
    title: 'Gaussian Filtering',
    hook: 'Weight neighbours by distance with a bell-shaped kernel.',
    unitId: 'spatial-filtering',
    order: 28,
    difficulty: 2,
    thumbnail: 'curve',
    prerequisites: ['smoothing'],
  },
  {
    slug: 'gaussian-function',
    title: 'Gaussian Function',
    hook: 'The bell curve itself: σ, peak height, and width.',
    unitId: 'spatial-filtering',
    order: 29,
    difficulty: 2,
    thumbnail: 'curve',
    prerequisites: ['gaussian-filtering'],
  },
  {
    slug: 'gaussian-weighting',
    title: 'Gaussian Weighting',
    hook: 'Greater distance, smaller weight. Compute one kernel entry.',
    unitId: 'spatial-filtering',
    order: 30,
    difficulty: 2,
    thumbnail: 'curve',
    prerequisites: ['gaussian-function'],
  },
  {
    slug: 'gaussian-smoothing',
    title: 'Gaussian Smoothing',
    hook: 'Denoise with σ: separable, composable, and tunable.',
    unitId: 'spatial-filtering',
    order: 31,
    difficulty: 2,
    thumbnail: 'curve',
    prerequisites: ['gaussian-weighting'],
  },
  {
    slug: 'edge-blurring',
    title: 'Edge Blurring',
    hook: 'The cost of smoothing: sharp edges become ramps.',
    unitId: 'spatial-filtering',
    order: 32,
    difficulty: 3,
    thumbnail: 'curve',
    prerequisites: ['gaussian-smoothing'],
  },

  // --- Unit 4: Bilateral Filtering ---
  {
    slug: 'bilateral-filtering',
    title: 'Bilateral Filtering',
    hook: 'Smooth flat regions, leave real edges alone: two weights instead of one.',
    unitId: 'bilateral-filtering',
    order: 33,
    difficulty: 2,
    thumbnail: 'matrix',
    prerequisites: ['edge-blurring'],
  },
  {
    slug: 'spatial-weight',
    title: 'Spatial Weight',
    hook: '"How far away is this neighbour?" — pure geometry, identical to Gaussian smoothing.',
    unitId: 'bilateral-filtering',
    order: 34,
    difficulty: 1,
    thumbnail: 'curve',
    prerequisites: ['bilateral-filtering'],
  },
  {
    slug: 'range-weight',
    title: 'Range / Intensity Weight',
    hook: '"How similar is this neighbour\'s brightness?" — the new ingredient that finds edges.',
    unitId: 'bilateral-filtering',
    order: 35,
    difficulty: 2,
    thumbnail: 'curve',
    prerequisites: ['spatial-weight'],
  },
  {
    slug: 'spatial-sigma',
    title: 'Spatial Standard Deviation σₛ',
    hook: 'How far the neighbourhood reaches, in pixels — the same σ as Gaussian filtering.',
    unitId: 'bilateral-filtering',
    order: 36,
    difficulty: 2,
    thumbnail: 'curve',
    prerequisites: ['range-weight'],
  },
  {
    slug: 'range-sigma',
    title: 'Range Standard Deviation σᵣ',
    hook: 'How tolerant the filter is to brightness gaps — push it to ∞ and bilateral collapses into Gaussian.',
    unitId: 'bilateral-filtering',
    order: 37,
    difficulty: 2,
    thumbnail: 'curve',
    prerequisites: ['spatial-sigma'],
  },
  {
    slug: 'bilateral-weight',
    title: 'Bilateral Weight',
    hook: 'Multiply spatial × range: a neighbour must be close AND similar to count.',
    unitId: 'bilateral-filtering',
    order: 38,
    difficulty: 2,
    thumbnail: 'matrix',
    prerequisites: ['range-sigma'],
  },
  {
    slug: 'edge-preserving-smoothing',
    title: 'Edge-Preserving Smoothing',
    hook: 'Watch the exact edge that blurred in Unit 3 stay sharp this time.',
    unitId: 'bilateral-filtering',
    order: 39,
    difficulty: 2,
    thumbnail: 'levels',
    prerequisites: ['bilateral-weight'],
  },
  {
    slug: 'patch-based-comparison',
    title: 'Patch-Based Comparison',
    hook: 'A single noisy pixel lies about similarity — compare small neighbourhoods instead.',
    unitId: 'bilateral-filtering',
    order: 40,
    difficulty: 3,
    thumbnail: 'matrix',
    prerequisites: ['edge-preserving-smoothing'],
  },
  {
    slug: 'patch',
    title: 'Patch',
    hook: 'A small fixed-size crop of pixels used as a pixel\'s local "signature".',
    unitId: 'bilateral-filtering',
    order: 41,
    difficulty: 1,
    thumbnail: 'matrix',
    prerequisites: ['patch-based-comparison'],
  },

  // --- Unit 5: Image Formation & Enhancement ---
  {
    slug: 'retinex',
    title: 'Retinex',
    hook: 'Recover how a surface truly looks, regardless of how it happens to be lit.',
    unitId: 'image-formation-enhancement',
    order: 42,
    difficulty: 2,
    thumbnail: 'levels',
    prerequisites: ['patch'],
  },
  {
    slug: 'illumination',
    title: 'Illumination',
    hook: 'L(x,y): the light falling on a scene — slow-varying, unrelated to the object itself.',
    unitId: 'image-formation-enhancement',
    order: 43,
    difficulty: 1,
    thumbnail: 'levels',
    prerequisites: ['retinex'],
  },
  {
    slug: 'reflectance',
    title: 'Reflectance',
    hook: 'R(x,y): the surface\'s intrinsic property — what we actually want to recover.',
    unitId: 'image-formation-enhancement',
    order: 44,
    difficulty: 1,
    thumbnail: 'levels',
    prerequisites: ['illumination'],
  },
  {
    slug: 'illumination-reflectance-model',
    title: 'Illumination–Reflectance Model',
    hook: 'I = L·R, and why taking logs turns a product into a sum you can separate.',
    unitId: 'image-formation-enhancement',
    order: 45,
    difficulty: 2,
    thumbnail: 'curve',
    prerequisites: ['reflectance'],
  },
  {
    slug: 'gamma-correction',
    title: 'Gamma Correction',
    hook: 'Why a flat brightness shift looks wrong, and what a power-law curve fixes.',
    unitId: 'image-formation-enhancement',
    order: 46,
    difficulty: 2,
    thumbnail: 'curve',
    prerequisites: ['illumination-reflectance-model'],
  },
  {
    slug: 'gamma-transformation',
    title: 'Gamma Transformation',
    hook: 's = c·r^γ, derived and probed — γ<1 brightens, γ>1 darkens.',
    unitId: 'image-formation-enhancement',
    order: 47,
    difficulty: 2,
    thumbnail: 'curve',
    prerequisites: ['gamma-correction'],
  },
  {
    slug: 'power-law-transformation',
    title: 'Power-Law Transformation',
    hook: 'The whole family of curves gamma correction belongs to — sweep γ and compare.',
    unitId: 'image-formation-enhancement',
    order: 48,
    difficulty: 2,
    thumbnail: 'curve',
    prerequisites: ['gamma-transformation'],
  },
];
